# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp

  target 'iosAppUITests' do
    # Pods for testing

    pod 'Embassy', '~> 4.1'
    pod 'EnvoyAmbassador', '~> 4.0'
  end

end
